### ISSUE TITLE
cant find the "php.ini" config file to increase upload_max_size

### ISSUE THREAD

**Issue by MixoMax** [illusion-c/FileServer#3]
The error mentions a php.ini file where i should be able to increas the max upload size but i cant find that. neither can I find a "PHP config" file.

**Comment by illusion-c** [comment]
Hi @MixoMax, 
`php.ini` file is not part of this project. It's a file that comes with Apache server installation. So, you have to find it in the apache configuration files in your system.

If you are using wamp, please check https://stackoverflow.com/questions/6185319/how-to-locate-the-php-ini-file-xampp. If you are on linux, refer https://stackoverflow.com/questions/8684609/where-can-i-find-php-ini.
